:recycle: Do not store window indexes as parameter
Avoids the following bug:
RuntimeError: Only Tensors of floating point dtype can require gradients
which is maybe related to this issue:
https://github.com/pytorch/pytorch/issues/32018